# Generated by Django 5.2.4 on 2025-07-29 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('police_station', models.CharField(max_length=255)),
                ('ob_number', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('date_found', models.DateTimeField()),
                ('found_location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='found_persons/')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('police_station', models.CharField(max_length=255)),
                ('ob_number', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('date_last_seen', models.DateTimeField()),
                ('last_seen_location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='lost_persons/')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('date_matched', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('found_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.foundperson')),
                ('lost_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.lostperson')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
