# Generated by Django 5.2.4 on 2025-07-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_confirmed',
        ),
    ]
