# Generated by Django 5.2.4 on 2025-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_match_confirmed_by_remove_match_is_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundperson',
            options={'ordering': ['-date_found']},
        ),
        migrations.AddField(
            model_name='foundperson',
            name='disability_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='date_found',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='ob_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='police_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='ob_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostperson',
            name='police_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
